# Generated by Django 5.1.6 on 2025-02-09 09:59

import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(help_text='Upload the problem statement as a PDF file.', upload_to=problems.models.problem_directory_path)),
                ('checker', models.FileField(help_text='Upload a checker script.', upload_to=problems.models.problem_directory_path)),
                ('test_cases', models.JSONField(help_text="List of test cases as dictionaries with 'input' and 'output' keys.")),
                ('time_limit', models.FloatField(default=1.0, help_text='Time limit in seconds')),
                ('memory_limit', models.IntegerField(default=256, help_text='Memory limit in MB')),
            ],
        ),
    ]
